version: '3'

networks:
  default:
    driver: bridge

volumes:
  db_data:
    driver: local
  npm_logs:
    driver: local

services:
  webserver:
    build:
      context: ./_docker
      dockerfile: Dockerfile
    container_name: webserver
    depends_on:
      - mariadb
    ports:
      - 8081:80
      - 3000:3000
      - 3001:3001
    volumes:
      - ./:/var/www
      - ./_docker/apache/000-default.conf:/etc/apache2/sites-available/000-default.conf
    networks:
      - default

  mariadb:
    image: mariadb:latest
    container_name: mariadb
    restart: unless-stopped
    tty: true
    ports:
      - 4306:3306
    volumes:
      - db_data:/var/lib/mysql
    environment:
      MYSQL_DATABASE: db
      MYSQL_USER: test
      MYSQL_PASSWORD: test
      MYSQL_ROOT_PASSWORD: root
      SERVICE_TAGS: dev
      SERVICE_NAME: mariadb
    networks:
      - default

  adminer:
    image: adminer
    restart: always
    ports:
      - 8082:8080
    depends_on:
      - mariadb
    networks:
      - default

  # composer:
  #   image: composer:latest
  #   container_name: composer
  #   volumes:
  #     - ./:/var/www
  #   networks:
  #     - default

  # npm:
  #   image: node:lts-alpine
  #   container_name: npm
  #   volumes:
  #     - ./:/var/www
  #     - npm_logs:/root/.npm/_logs
  #   working_dir: /var/www
  #   entrypoint: ['npm']
  #   ports:
  #     - 3000:3000
  #     - 3001:3001
  #   networks:
  #     - default

  # artisan:
  #   build:
  #     context: ./_docker
  #     dockerfile: Dockerfile
  #   container_name: artisan
  #   volumes:
  #     - ./:/var/www
  #   depends_on:
  #     - mariadb
  #   working_dir: /var/www
  #   entrypoint: ['/var/www/artisan']
  #   networks:
  #     - default
