version: '3.3'

volumes:
  db_data: {}

services:
  php:
    build:
      context: .
      dockerfile: ./Dockerfile
    image: php_apache
    ports:
      - 8000:80
    volumes:
      - .:/var/www/html/app
    links:
      - db
    environment:
      DB_HOST: db
      DB_DATABASE: test
      DB_USERNAME: test
      DB_PASSWORD: test

  db:
    image: mariadb
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: test
      MYSQL_USER: test
      MYSQL_PASSWORD: test
      MYSQL_ROOT_PASSWORD: test
    volumes:
      - db_data:/var/lib/mysql/data